name: 🐛 Bug Report
description: Create a report to help us improve
title: '[Bug]: '
labels: ['bug', 'needs-triage']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-flight Checklist
      description: Please ensure you've completed these steps before submitting a bug report
      options:
        - label: I have searched for existing issues that describe this bug
          required: true
        - label: I am using the latest version of @shanfu/ui
          required: true
        - label: I have read the documentation
          required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of @shanfu/ui are you using?
      placeholder: '1.0.0'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: 'Describe the bug...'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: 'Describe what should happen...'
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: 'Describe what actually happens...'
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Please provide a minimal code example that reproduces the issue
      render: tsx
      placeholder: |
        import { Component } from '@shanfu/ui';

        function App() {
          return <Component />;
        }

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) does this affect?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: 'macOS 14, Windows 11, Ubuntu 22.04'

  - type: input
    id: node
    attributes:
      label: Node.js Version
      description: Which version of Node.js are you using?
      placeholder: '18.17.0'

  - type: dropdown
    id: framework
    attributes:
      label: React Framework
      description: Which React framework are you using?
      options:
        - Create React App
        - Next.js
        - Vite
        - Remix
        - Gatsby
        - Other
        - None (plain React)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: 'Screenshots, error messages, etc.'

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help fix this bug
